(* This file was generated by: gen/gen.exe ml *)

open Types

external openat
  :  dir:Fd.t
  -> path:string
  -> flags:Open_flag.t list
  -> perm:File_perm.t
  -> Fd.t
  = "shexp_openat"

external faccessat
  :  dir:Fd.t
  -> path:string
  -> mode:Access_permission.t list
  -> flags:At_flag.t list
  -> unit
  = "shexp_faccessat"

external fchmodat
  :  dir:Fd.t
  -> path:string
  -> perm:File_perm.t
  -> flags:At_flag.t list
  -> unit
  = "shexp_fchmodat"

external fchownat
  :  dir:Fd.t
  -> path:string
  -> uid:int
  -> gid:int
  -> flags:At_flag.t list
  -> unit
  = "shexp_fchownat"

external mkdirat
  :  dir:Fd.t
  -> path:string
  -> perm:File_perm.t
  -> unit
  = "shexp_mkdirat"

external unlinkat
  :  dir:Fd.t
  -> path:string
  -> flags:At_flag.t list
  -> unit
  = "shexp_unlinkat"

external mkfifoat
  :  dir:Fd.t
  -> path:string
  -> perm:File_perm.t
  -> unit
  = "shexp_mkfifoat"

external linkat
  :  olddir:Fd.t
  -> oldpath:string
  -> newdir:Fd.t
  -> newpath:string
  -> flags:At_flag.t list
  -> unit
  = "shexp_linkat"

external renameat
  :  olddir:Fd.t
  -> oldpath:string
  -> newdir:Fd.t
  -> newpath:string
  -> unit
  = "shexp_renameat"

external symlinkat
  :  oldpath:string
  -> newdir:Fd.t
  -> newpath:string
  -> unit
  = "shexp_symlinkat"
